### ISSUE TITLE
Error resource [v1/List] isn't valid for cluster

### ISSUE THREAD

**Issue by javier-ga** [gavinbunney/terraform-provider-kubectl#12]
Thanks for the provider. It is really useful.

The `kubectl` client the provider uses does not support defining yaml files with List types

```
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: list-service-test
  spec:
    ports:
    - protocol: TCP
      port: 80
    selector:
      app: list-deployment-test
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: list-deployment-test
    labels:
      app: list-deployment-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: list-deployment-test
    template:
      metadata:
        labels:
          app: list-deployment-test
      spec:
        containers:
          - name: nginx
            image: nginx
```

If I run this with the provider I get the following error:

```
module.cluster.module.kube_config.kubectl_manifest.example: Creating...

Error: failed to create kubernetes rest client for update of resource: resource [v1/List] isn't valid for cluster, check the APIVersion and Kind fields are valid
```

This is the format `kubectl` uses to generates yaml output files that contain multiple resources.

Here are the terraform versions I am using
```
Terraform v0.12.12
+ provider.aws v2.42.0
+ provider.http v1.1.1
+ provider.kubectl (unversioned)
+ provider.kubernetes v1.10.0
```
