### ISSUE TITLE
Cannot import CRD definition

### ISSUE THREAD

**Issue by headyj** [gavinbunney/terraform-provider-kubectl#158]
I cannot import an existing resource in my state using the provided documentation:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqclusters.rabbitmq.com
```

```
terraform import kubectl_manifest.rabbitmq_clusters
apiextensions.k8s.io/v1//CustomResourceDefinition//rabbitmqclusters.rabbitmq.com
module.eks_ci_initial_setup.kubectl_manifest.rabbitmq_clusters[0]: Importing from ID "apiextensions.k8s.io/v1//CustomResourceDefinition//rabbitmqclusters.rabbitmq.com"...
╷
│ Error: failed to get resource apiextensions.k8s.io/v1 CustomResourceDefinition rabbitmqclusters.rabbitmq.com from kubernetes: customresourcedefinitions.apiextensions.k8s.io "rabbitmqclusters.rabbitmq.com" not found
```

As you can see, it says that the rabbitmqclusters.rabbitmq.com crd does not exist, but it does:

```
kubectl get crd rabbitmqclusters.rabbitmq.com -o jsonpath='{.apiVersion}:{.metadata.name}'
apiextensions.k8s.io/v1:rabbitmqclusters.rabbitmq.com
```
