### ISSUE TITLE
<name> failed to fetch resource from kubernetes: the server could not find the requested resource

### ISSUE THREAD

**Issue by filipvh-sentia** [gavinbunney/terraform-provider-kubectl#270]
# The issue

I'm running into an error with karpenter yaml templates and I'm unsure on what the cause is. I've used the `kubectl_manifest` in the past and it worked fine on consecutive applies, but for some reason it's not working with the

Sample YAML file:

```
            apiVersion: rbacmanager.reactiveops.io/v1beta1
            kind: RBACDefinition
            metadata:
              name: permissionsets
            rbacBindings:
            - clusterRoleBindings:
              - clusterRole: view
              name: readonly
              subjects:
              - kind: Group
                name: core:group:readonly
            - clusterRoleBindings:
              - clusterRole: view
              name: maintenance-view
              subjects:
              - kind: Group
                name: core:group:maintenance
            - clusterRoleBindings:
              - clusterRole: edit_extra_permissions
              name: maintenance-additions
              subjects:
              - kind: Group
                name: core:group:maintenance
            - name: maintenance
              roleBindings:
              - clusterRole: edit
                namespaceSelector:
                  matchExpressions:
                  - key: system-protected
                    operator: NotIn
                    values:
                    - "true"
              subjects:
              - kind: Group
                name: core:group:maintenance
            - clusterRoleBindings:
              - clusterRole: admin
              name: administrator
              subjects:
              - kind: Group
                name: core:group:admin
```

When I try to apply it through terraform it will plan just fine, but when I try to apply it, it gives me the following error:

```
╷
│ Error: permissionsets failed to fetch resource from kubernetes: the server could not find the requested resource
│ 
│   with module.core_system.kubectl_manifest.permissions-sets[0],
│   on ......./rbac-addon.tf line 123, in resource "kubectl_manifest" "permissions-sets":
│  123: resource "kubectl_manifest" "permissions-sets" {
│ 
╵
```
I don't know where to start looking to resolve this. The items never show up in the statefile, but the objects are created inside the cluster. It looks like it created them and tries to find them, but then doesn't seem to find them?

I'll keep digging as this provider is my only way of applying yamls to the cluster through terraform without using `null_resource` ( dirty last resort hack imo ) or the `kubernetes_manifest` ( which doesn't work if the CRDs don't exist ).
