### ISSUE TITLE
Generating yaml from a terraform template file

### ISSUE THREAD

**Issue by linuxbsdfreak** [gavinbunney/terraform-provider-kubectl#29]
Hi @gavinbunney 

I had a look at this snippet below. Can i use a generated yaml from a template file ? Since i would like to create a module for common K8s resources and then change it for each environment 

```
resource "kubectl_manifest" "test" {
    yaml_body = <<YAML
apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: name-here-cluster
spec:
  baseImage: name-here-image
  version: name-here-image-version
  authSecret: name-here-operator-secret-name
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 120
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
YAML
}
```

Do you have some sample of using templates or are you using the raw K8s manifest 

Kevin
