### ISSUE TITLE
Only first YAML document gets applied

### ISSUE THREAD

**Issue by iamtakingiteasy** [gavinbunney/terraform-provider-kubectl#52]
How to reproduce:

```
resource "kubectl_manifest" "manifests" {  
  yaml_body = <<YAML
apiVersion: v1
kind: Namespace
metadata:
  name: foo
  annotations:
  labels:
    name: foo
---
apiVersion: v1
kind: Namespace
metadata:
  name: bar
  annotations:
  labels:
    name: bar
YAML
}
```

Here only `foo` namespace will be created.
It is common practice in many kubernetes YAML sheets and deployment resources to include multiple documents in one file.
Ignoring all documents after the first will cause incomplete deployments when using existing external manifests, such as calico's https://docs.projectcalico.org/manifests/tigera-operator.yaml
