### ISSUE TITLE
[cert-manager.io/v1/ClusterIssuer] isn't valid for cluster, check the APIVersion and Kind fields are valid

### ISSUE THREAD

**Issue by boubech** [gavinbunney/terraform-provider-kubectl#56]
Hello,

I have upgrade the provider and I can't deploy custom manifest bellow.
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contact@kexample.org
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik
```

The clusterissuers is present in API resource of Kubernetes.

Regards,
