### ISSUE TITLE
Additional validation during plan

### ISSUE THREAD

**Issue by mcristina422** [gavinbunney/terraform-provider-kubectl#99]
To help catch failures, we should validate the resource name is a valid kubernetes name. In the following example, variable interpolation is incorrect due to user error (note the `$$` instead of `$`). When reading a resource during a plan we could use the [apimachinery validation package](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation.go) to error during the plan instead of hitting an error during apply 

```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: foo-$${index}
```
